trigger:
  branches:
    include:
      - main

variables:
  sshServiceConnection: 'anvarlab'
  containerRegistry: 'dockerhub'
  repository: 'ggsa/fuddyduddy'
  # Backend variables
  backendDockerfile: 'src/Application/FuddyDuddy.Api/Dockerfile'
  # Frontend variables
  frontendDockerfile: 'src/Application/fuddyduddy-web-react/Dockerfile'
  # Build configuration
  buildConfiguration: 'Release'

stages:
- stage: Test
  displayName: Test stage
  jobs:
  - job: RunTests
    displayName: Run Tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    # Setup .NET
    - task: UseDotNet@2
      displayName: 'Install .NET 9'
      inputs:
        version: '9.0.x'
        includePreviewVersions: true

    # Restore dependencies
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: 'FuddyDuddy.sln'

    # Run Core tests
    - task: DotNetCoreCLI@2
      displayName: 'Run Core Tests'
      inputs:
        command: test
        projects: 'tests/FuddyDuddy.Core.Tests/FuddyDuddy.Core.Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'

    # Run API tests
    - task: DotNetCoreCLI@2
      displayName: 'Run API Tests'
      inputs:
        command: test
        projects: 'tests/FuddyDuddy.Api.Tests/FuddyDuddy.Api.Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'

    # Publish code coverage results
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        failIfCoverageEmpty: false

- stage: BuildAndPush
  displayName: Build and push stage
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    # Login to Docker Hub
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(containerRegistry)

    # Handle backend image
    - task: Bash@3
      displayName: 'Manage Backend Image Tags'
      inputs:
        targetType: 'inline'
        script: |
          # Pull latest (if exists) and retag as previous
          if docker pull $(repository):api-latest; then
            docker tag $(repository):api-latest $(repository):api-previous
            docker push $(repository):api-previous
          fi

    - task: Docker@2
      displayName: Build Backend Docker image
      inputs:
        command: build
        repository: $(repository)
        Dockerfile: $(backendDockerfile)
        buildContext: .
        tags: api-latest

    - task: Docker@2
      displayName: Push Backend Docker image
      inputs:
        command: push
        repository: $(repository)
        tags: api-latest

    # Handle frontend image
    - task: Bash@3
      displayName: 'Manage Frontend Image Tags'
      inputs:
        targetType: 'inline'
        script: |
          # Pull latest (if exists) and retag as previous
          if docker pull $(repository):web-latest; then
            docker tag $(repository):web-latest $(repository):web-previous
            docker push $(repository):web-previous
          fi

    - task: Docker@2
      displayName: Build Frontend Docker image
      inputs:
        command: build
        repository: $(repository)
        Dockerfile: $(frontendDockerfile)
        buildContext: .
        tags: web-latest

    - task: Docker@2
      displayName: Push Frontend Docker image
      inputs:
        command: push
        repository: $(repository)
        tags: web-latest

    # Logout from Docker Hub
    - task: Docker@2
      displayName: Logout from Docker Hub
      inputs:
        command: logout
        containerRegistry: $(containerRegistry)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: BuildAndPush
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none

          - task: SSH@0
            displayName: 'Deploy to VPS'
            inputs:
              sshEndpoint: $(sshServiceConnection)
              runOptions: inline
              inline: |
                cd /root/docker
                pwd
                echo `date` ": starting azure pipeline build $(Build.BuildNumber)" >> azure-pipeline.log
                # Pull latest images
                docker pull $(repository):api-latest >> azure-pipeline.log
                docker pull $(repository):web-latest >> azure-pipeline.log
                # Update services
                docker compose up -d --no-deps --build fuddyduddy-api fuddyduddy-web >> azure-pipeline.log
                echo `date` ": succeed azure pipeline build" >> azure-pipeline.log 
              readyTimeout: '60000'
              failOnStdErr: false