### variables
@apiKey = 8F66EC3F-99D4-4C87-A4E6-0F8A9D7BFEC3
@baseUrl = https://api.fuddy-duddy.org
@localApiKey = fuddy-duddy-secret
@localBaseUrl = http://localhost:5102

### get news summaries
GET {{baseUrl}}/api/summaries
Content-Type: application/json

### get news summaries
GET {{baseUrl}}/api/summaries
Content-Type: application/json

### rebuild cache
POST {{baseUrl}}/api/maintenance/rebuild-cache
Content-Type: application/json
api-key: {{apiKey}}

### revisit categories
POST {{baseUrl}}/api/maintenance/revisit-categories/20250111T1347
Content-Type: application/json
api-key: {{apiKey}}

### sitemap
GET {{baseUrl}}/sitemap.xml
Content-Type: text/xml

### remove similar reference
POST {{baseUrl}}/api/maintenance/delete-similar-reference/2a5a428d-3e6c-4f5e-93ae-13f063259513
Content-Type: application/json
api-key: {{apiKey}}

### update summary in cache
POST {{baseUrl}}/api/maintenance/update-cache/summaries/b9dae521-fc5d-4fa6-a1dd-5c052de4b29b
Content-Type: application/json
api-key: {{apiKey}}

### delete similar
POST {{baseUrl}}/api/maintenance/delete-similar/02e32cd4-08c7-433b-9d59-3af57196104e
Content-Type: application/json
api-key: {{apiKey}}

### PROD: rebuild vector index
POST {{baseUrl}}/api/maintenance/rebuild-vector-index?skipDelete=true&indexType=Titles
Content-Type: application/json
api-key: {{apiKey}}

### PROD: chromadb search query news_summaries collection
POST {{baseUrl}}/api/search/summaries
Content-Type: application/json

{
    "query": "где находился Садыр Жапаров президент Кыргызстана до 15 january 2025",
    "limit": 2,
    "language": 0
}


###----------------Local test endpoints----------------###

### revisit categories
GET {{localBaseUrl}}/api/maintenance/revisit-categories?since=20250110T0536
Content-Type: application/json
api-key: {{localApiKey}}

### rebuild cache
POST {{localBaseUrl}}/api/maintenance/rebuild-cache
Content-Type: application/json
api-key: {{localApiKey}}

### generate digest
POST {{localBaseUrl}}/api/digests/generate?language=RU
Content-Type: application/json

### generate digest
GET {{localBaseUrl}}/api/summaries?language=RU&pageSize=10&page=0
Content-Type: application/json
Host: localhost1

### rebuild vector index
POST {{localBaseUrl}}/api/maintenance/rebuild-vector-index?skipDelete=true&indexType=Titles
Content-Type: application/json
api-key: {{localApiKey}}

### qdrant search query news_summaries collection
POST {{localBaseUrl}}/api/search/summaries
Content-Type: application/json

{
    "query": "зеленая энергия",
    "limit": 2,
    "language": 0
}

### test extract date range
POST {{localBaseUrl}}/api/maintenance/extract-date-range
Content-Type: application/json
api-key: {{localApiKey}}

# "Куда летал президент в феврале 2024?"
# "Куда летал президент c 1 по 25 декабря 2024?"
# "что было вчера?"
# "где был президент позавчера?"
# "где был президент три дня назад?"
# "что было с позавчера по вчера?"
# "что делал президент сегодня?"
# "что делал президент вчера?"
# "что делал президент позавчера?"
# "что делал президент сегодня и вчера?"
# "что делал президент сегодня и позавчера?"
# "что делал президент с позавчера по вчера и сегодня?"
# "что делал президент с позавчера по вчера и три дня назад?"
# "что делал президент с вчера по завтра?"
# "что делал президент с позавчера по завтра?"
# "что делал президент с три дня назад по завтра?"
# "что делал президент с позавчера по завтра и три дня назад?"
