version: '3.8'

services:
  # Message broker
  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=fuddy
      - RABBITMQ_DEFAULT_PASS=duddy
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  # Database
  mysql:
    image: mysql:8.0.40
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fuddyduddy
      - MYSQL_USER=fuddy
      - MYSQL_PASSWORD=duddy
    volumes:
      - ./data/mysql:/var/lib/mysql

  # Search engine
  elasticsearch:
    image: elasticsearch:8.12.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  # Cache
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  # Object storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    environment:
      - MINIO_ROOT_USER=fuddy
      - MINIO_ROOT_PASSWORD=duddy123
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"