import type { Language } from '../contexts/LanguageContext'

interface Translation {
  header: {
    title: string
    subtitle: string
    about: string
    digests: string
  }
  filters: {
    title: string
    categories: string
    sources: string
    language: string
    clearAll: string
  }
  digests: {
    title: string
    generatedEveryHour: string
    viewAll: string
  }
  about: {
    title: string
    description: string
    disclaimer: string
    howItWorks: {
      title: string
      step1: string
      step2: string
      step3: string
    }
    legal: {
      title: string
      copyright: string
      disclaimer: string
      aiDisclaimer: string
      responsibility: string
      contentWarning: string
    }
    privacy: {
      title: string
      dataCollection: string
      cookies: string
      thirdParty: string
    }
    contact: {
      title: string
      description: string
      email: string
    }
  }
  common: {
    readMore: string
    share: string
    loading: string
    error: string
    retry: string
    originalSource: string
    newSummariesAvailable: string
    loadMore: string
    backToFeed: string
  }
  errors: {
    failedToLoadDigests: string
  }
}

const translations: Record<Language, Translation> = {
  EN: {
    header: {
      title: 'FuddyDuddy News',
      subtitle: 'News from Kyrgyzstan',
      about: 'About',
      digests: 'Digests'
    },
    filters: {
      title: 'Filters',
      categories: 'Categories',
      sources: 'Sources',
      language: 'Language',
      clearAll: 'Clear all'
    },
    digests: {
      title: 'Latest Digests',
      generatedEveryHour: 'Digests are generated every hour',
      viewAll: 'View all digests'
    },
    about: {
      title: 'About FuddyDuddy News',
      description: 'FuddyDuddy News aggregates news from various Kyrgyzstan news agencies, using AI to rephrase titles and summarize articles for better readability.',
      disclaimer: 'All news content belongs to respective news agencies. Each summary contains a reference to the source and a link to the original article.',
      howItWorks: {
        title: 'How It Works',
        step1: 'We collect news articles from trusted Kyrgyzstan news agencies through their official RSS feeds and sitemaps.',
        step2: 'Our AI system processes each article, creating concise summaries while preserving the key information.',
        step3: 'Every summary includes a link to the original article, allowing you to read the full content on the source website.'
      },
      legal: {
        title: 'Legal Information',
        copyright: 'All news content, including text and media, belongs to their respective owners and news agencies.',
        disclaimer: 'FuddyDuddy News is an aggregator and does not create original news content. We provide AI-generated summaries of existing articles.',
        aiDisclaimer: 'While we strive for accuracy, please note that our summaries are generated by AI and should not be considered official translations or representations of the original articles.',
        responsibility: 'FuddyDuddy News is not responsible for the content of the original articles or any inaccuracies in the AI-generated summaries. Please refer to the original sources for official information.',
        contentWarning: 'Please note that due to the automated nature of our service, content on this site may contain errors, inappropriate phrases, or inaccurate translations. We recommend always verifying information with official sources.'
      },
      privacy: {
        title: 'Privacy Information',
        dataCollection: 'We collect minimal data necessary for the service to function, such as your language preference and theme settings.',
        cookies: 'We use essential cookies to remember your preferences and improve your browsing experience.',
        thirdParty: 'Links to original articles will take you to third-party news websites, which have their own privacy policies and terms of service.'
      },
      contact: {
        title: 'Contact Us',
        description: 'If you have any questions, concerns, or feedback, please feel free to contact us at:',
        email: 'hey@fuddy-duddy.org'
      }
    },
    common: {
      readMore: 'Read full article',
      share: 'Share',
      loading: 'Loading...',
      error: 'Something went wrong',
      retry: 'Try again',
      originalSource: 'Original source',
      newSummariesAvailable: 'New summaries available. Click to refresh.',
      loadMore: 'Load more',
      backToFeed: 'Back to news feed'
    },
    errors: {
      failedToLoadDigests: 'Failed to load digests'
    }
  },
  RU: {
    header: {
      title: 'FuddyDuddy News',
      subtitle: 'Новости Кыргызстана',
      about: 'О проекте',
      digests: 'Дайджесты'
    },
    filters: {
      title: 'Фильтры',
      categories: 'Категории',
      sources: 'Источники',
      language: 'Язык',
      clearAll: 'Очистить все'
    },
    digests: {
      title: 'Последние дайджесты',
      generatedEveryHour: 'Дайджесты генерируются каждый час',
      viewAll: 'Смотреть все дайджесты'
    },
    about: {
      title: 'О FuddyDuddy News',
      description: 'FuddyDuddy News агрегирует новости из различных информационных агентств Кыргызстана, используя ИИ для перефразирования заголовков и создания кратких обзоров статей.',
      disclaimer: 'Все новости принадлежат соответствующим информационным агентствам. Каждый обзор содержит ссылку на источник и оригинальную статью.',
      howItWorks: {
        title: 'Как это работает',
        step1: 'Мы собираем новости из проверенных информационных агентств Кыргызстана через их официальные RSS-ленты и карты сайтов.',
        step2: 'Наша система ИИ обрабатывает каждую статью, создавая краткие обзоры с сохранением ключевой информации.',
        step3: 'Каждый обзор включает ссылку на оригинальную статью, позволяя вам прочитать полный текст на сайте источника.'
      },
      legal: {
        title: 'Правовая информация',
        copyright: 'Все новостные материалы, включая текст и медиа, принадлежат соответствующим владельцам и информационным агентствам.',
        disclaimer: 'FuddyDuddy News является агрегатором и не создает оригинальный новостной контент. Мы предоставляем сгенерированные ИИ обзоры существующих статей.',
        aiDisclaimer: 'Несмотря на то, что мы стремимся к точности, обратите внимание, что наши обзоры генерируются ИИ и не должны рассматриваться как официальные переводы или представления оригинальных статей.',
        responsibility: 'FuddyDuddy News не несет ответственности за содержание оригинальных статей или какие-либо неточности в сгенерированных ИИ обзорах. Пожалуйста, обращайтесь к оригинальным источникам для получения официальной информации.',
        contentWarning: 'Обратите внимание, что из-за автоматизированного характера нашего сервиса, контент на сайте может содержать ошибки, некорректные фразы или неточные переводы. Мы рекомендуем всегда проверять информацию в официальных источниках.'
      },
      privacy: {
        title: 'Информация о конфиденциальности',
        dataCollection: 'Мы собираем минимальные данные, необходимые для работы сервиса, такие как ваши языковые предпочтения и настройки темы.',
        cookies: 'Мы используем необходимые файлы cookie для сохранения ваших предпочтений и улучшения работы с сайтом.',
        thirdParty: 'Ссылки на оригинальные статьи ведут на сторонние новостные сайты, которые имеют свою политику конфиденциальности и условия использования.'
      },
      contact: {
        title: 'Связаться с нами',
        description: 'Если у вас есть вопросы, замечания или предложения, пожалуйста, свяжитесь с нами по адресу:',
        email: 'hey@fuddy-duddy.org'
      }
    },
    common: {
      readMore: 'Читать полностью',
      share: 'Поделиться',
      loading: 'Загрузка...',
      error: 'Что-то пошло не так',
      retry: 'Попробовать снова',
      originalSource: 'Оригинальный источник',
      newSummariesAvailable: 'Доступны новые новости. Нажмите, чтобы обновить.',
      loadMore: 'Загрузить еще',
      backToFeed: 'Вернуться к ленте новостей'
    },
    errors: {
      failedToLoadDigests: 'Не удалось загрузить дайджесты'
    }
  }
}

export function useTranslations(language: Language) {
  return translations[language]
} 